### ISSUE TITLE
Chap 2 : Adding Comments : Issue is that Same Comment get Posted as many times as we reload the Page after posting 1 comment on the Post 

### ISSUE THREAD

**Issue by faisalnazik** [PacktPublishing/Django-3-by-Example#49]
I want to Fix that ... Please let me know how to do that . Because a User can Comment same many times if he just reloading the same which on which he commented. 
Thank You

**Comment by anselbo** [comment]
Is the same problem that am still facing, the suggestion i have would have be to redirect the page to another page after the comment  has been successfully posted but if we need to still redirect to the same page after the comment has been been posted, for sure, the problem keep happening and  this is where the problem is.

**Comment by kp9995** [comment]
simply redirect the page to another page or same page to avoid re posting the comment upon reload.

**Comment by faisalnazik** [comment]
Thank You for the help ..
