### ISSUE TITLE
Chapter 6: Not Found: /account/users/follow/

### ISSUE THREAD

**Issue by mjavadf** [PacktPublishing/Django-3-by-Example#7]
hi.
I've done **Building a follow system** and run the server and try following a user but it gets me this error:
```
Not Found: /account/users/follow/
[26/May/2020 17:24:58] "POST /account/users/follow/ HTTP/1.1" 404 1757
```
I copied `domready block`, url path and `views.user_follow` from github but have problem yet

**Comment by mjavadf** [comment]
I fixed this problem.
before fixing urlpatterns was like this:
```
urlpatterns = [
    ...
    path('users/', views.user_list, name='user_list'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    path('users/follow/', views.user_follow, name='user_follow'),
]
```
and then I edit it like this:
```
urlpatterns = [
    ...
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
]
```

why this happened?

**Comment by LeonT-A** [comment]
When looking for a matching URL pattern, Django scans all the paths from top-to-bottom.

Your user_detail path and your user_follow path share a similar pattern (What if the username is 'follow'?), so Django was matching the user_detail before it ever got to user_follow.

Order matters, make sure to put the stricter urlpatterns first so that they can be matched correctly, otherwise a more flexible pattern might take the match by accident.
